### ISSUE TITLE
Wildcard in path

### ISSUE THREAD

**Issue by francisprovost** [dotronglong/faker#32]
Hi!

I was trying to use your project to mock one of my api and I find a use case that I'm not sure is supported or that I didn't find how to do it.

I have an endpoint where the URL is something like `/toto/find?startDate=2020-04-26&endDate=2020-05-02`. I was looking for a way to always return the same data whatever the `startDate` and `endDate` are. Is it something possible right now?

Thanks

**Comment by dotronglong** [comment]
Yes, it is possible using regexp in path, can you try to put following in
path:  ^\\/toto\\/find\\?startDate=\\d+\\-\\d+\\-\\d+\\&endDate=\\d+\\-\\d+
\\-\\d+$

Thanks in advance,
*Long Do Trong*
*E*   me@dotronglong.com
*P*   09 1450 1450

This e-mail is confidential. It may also be legally privileged. If you are
not the addressee you may not copy, forward, disclose or use any part of
it. If you have received this message in error, please delete it and all
copies from your system and notify the sender immediately by return e-mail.
Internet communications cannot be guaranteed to be timely, secure, error or
virus-free. The sender does not accept liability for any errors or
omissions.
"SAVE THE PLANET - THINK CARE BEFORE PRINT!"

**Comment by francisprovost** [comment]
oh perfect! It totally does work!

Thanks for the lib!
