### ISSUE TITLE
Check mock requests body

### ISSUE THREAD

**Issue by mfamador** [dotronglong/faker#33]
Hi!
I was trying to create some POST mocks on which I want to get different responses depending on the request body values.
I'm struggling to retrieve the request body on JsonRouter from the ServerHttpRequest object so that I can match the requests to the mock specs.
Do you have any idea how could we get the body contents here?
Thanks!

**Comment by maaroofunbxd** [comment]
can you comment on the issue?
i thiink the request body does not matter in the mock?

**Comment by dotronglong** [comment]
@maaroofunbxd Yes, I think it's harder to parse the body, and not really make much sense. However, if you have any idea to implement it, you're welcome to make PR.
