### ISSUE TITLE
Middle Layer

### ISSUE THREAD

**Issue by ztobs** [dotronglong/faker#35]
Can I use this fake API as a layer between my application and the real API?
I still want to test different scenarios which varies with the API post body parameters in the requests which fake APi cannot.

In short I want my application to still behave like before except for having control over the latency/response time

**Comment by dotronglong** [comment]
Hi, this faker is used for testing purposes rather than production purposes. In order to support more scenarios, there will be the needs of development.

**Comment by ztobs** [comment]
> Hi, this faker is used for testing purposes rather than production purposes. In order to support more scenarios, there will be the needs of development.

This obviously isn't an issue, its just a suggestion and its still a testing feature not for production.

I definitely wouldn't want to add a latency to a live production, its for sure for testing. May I would add my contribution because I love your project and was really helpful for me

**Comment by dotronglong** [comment]
Yes definitely, I welcome any contributions
