### ISSUE TITLE
Mock endpoint aren't available.

### ISSUE THREAD

**Issue by rowanfuchs** [dotronglong/faker#36]
I've configured a mock server as per your documtentation however, I receive a 404 on the following endpoints:
http://localhost:3030/products
http://localhost:3030/v1/products

config:
![image](https://user-images.githubusercontent.com/48676736/160230081-ddd18f36-ccda-4513-b220-33b1cdf090bb.png)

docker-compose.yml
`version: '3'

services:
  faker:
    container_name: faker
    image: dotronglong/faker:stable
    ports:
      - "3030:3030"
    volumes:
      - ./mocks:/app/mocks`

products.json
`{
    "request": {
        "scheme": "http",
        "host": "localhost",
        "port": 3030,
        "method": "get",
        "path": "/products",
        "headers": {
            "content-type": "application/json"
        }
    },
    "response": {
        "statusCode": 200,
        "headers": {
            "content-type": "application/json; charset=utf-8"
        },
        "body": []
    }
}
`

**Comment by dotronglong** [comment]
Hi @rowanfuchs I am so sorry that I didn’t answer it on time as I didn’t receive the notification for this request. Did you manage to solve it?

**Comment by rowanfuchs** [comment]
Hi @dotronglong no worries, thank you for looking into it, I am not sure what went wrong last time (maybe I accessed it via https or something) however when I try it again with the default as explained in the readme I receive the following error: 
```
2023-01-26 09:47:49.512 ERROR 1 --- [           main] c.d.faker.service.router.JsonRouter      : Unable to read file. Exception: Unexpected character ('' (code 65279 / 0xfeff)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"{
  "plugins": [
    {
      "name": "list",
      "args": {
        "count": 5,
        "item": {
          "id": "#random:int:min=1&max=1000#",
          "name": "#random:name#",
          "created_at": "#timestamp#",
          "updated_at": "#timestamp#"
        }
      }
    },
    {
      "name": "random"
    },
    {
      "name": "timestamp"
    }
  ],
  "request": {
    "method": "GET",
    "path": "/v1/users"
  },
  "response": {
    "body": []
  }
}
"; line: 1, column: 2]
```

**Comment by rowanfuchs** [comment]
allright, ignore my last comment. Somehow Windows decided adding a DOM to the file would be a smart idea. Once I removed this with my IDE it started working. Thank you for this amazing app!

**Comment by dotronglong** [comment]
I am glad it helps you.
