### ISSUE TITLE
How can I use multiple file nesting levels?

### ISSUE THREAD

**Issue by yarkovaleksei** [dotronglong/faker#39]
```
./app/mocks
└── cards
    └── Employees
        └── Menu.json
    └── Tests
        └── Parent.json
        └── Child.json
```

**Comment by dotronglong** [comment]
Hi @yarkovaleksei , I don’t think this option is available at this moment, however, why don’t you place only files instead, for example, card_Employees_Menu.json

**Comment by yarkovaleksei** [comment]
@dotronglong I add PR for this issue - https://github.com/dotronglong/faker/pull/41
