### ISSUE TITLE
Question about Admin UI

### ISSUE THREAD

**Issue by yarkovaleksei** [dotronglong/faker#44]
@dotronglong Hello. 
I have already made changes to the project several times. I use it in my projects and I really like it. I came up with the idea to make an admin interface where you could manage fixtures (create, edit and delete). On this issue, I would like advice on how best to do it. 

**Option 1**
Make it in the same repository and listen to its port when the application starts.

**Option 2** 
Make a separate repository that can be published to Docker Hub with a name such as faker-admin-ui.

What do you think about this?

**Comment by dotronglong** [comment]
Thank you @yarkovaleksei , I also thought about it long time ago, however, I didn't have time to make it. The idea is great, I would love to choose option 2 so we can keep the original repository clean and tidy. In the homepage (or README file) of this repository we will mention about additional tools admin ui for it.

Additionally, do you have any experiences or knowledge about front end, which tools / frameworks would you use?

**Comment by yarkovaleksei** [comment]
@dotronglong I have a lot of experience with Vue on the front end. For the backend, I would choose Nest.js. This is the best API building framework I've ever used.

**Comment by yarkovaleksei** [comment]
@dotronglong I'll let you know when an approximate plan with a description of the functionality is ready. Thank you ))

**Comment by dotronglong** [comment]
That's great, can't wait to see it.
