### ISSUE TITLE
HTTPS connection with docker image?

### ISSUE THREAD

**Issue by fchris82** [dotronglong/faker#49]
Hello,

I want to use a fake API but the configuration accepts only https. If I try to call this one: `https://test_api:3030/api/v2/get-something.json?id=30` I get this error: `error:1408F10B:SSL routines:ssl3_get_record:wrong version number` .

Is there any solution to this? Or should I hack the config to accept HTTP URL?

**Comment by yarkovaleksei** [comment]
@fchris82 Hello. I would recommend delegating work with https to some proxy like Traefik. For development, you can use self-signed certificates and mkcert.

**Comment by dotronglong** [comment]
@fchris82 I also have the same idea with @yarkovaleksei , this application should not focus on HTTPS specifically.
