### ISSUE TITLE
Latest docker image broken 

### ISSUE THREAD

**Issue by John-A-J** [dotronglong/faker#54]
Hello,

Thanks for writing and maintaining faker. We started using it this week. Unfortunately I spent all this morning trying to diagnose a problem when I was running faker in github actions. The logs I eventually got were
```
 **********************************************************************
  * Name  : mocks_mystic_1
  * Image : dotronglong/faker:stable
  * Status: Exited (1) 2 minutes ago
  **********************************************************************
  Error: A JNI error has occurred, please check your installation and try again
  Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/JarLauncher has been compiled by a more recent version of the Java Runtime 
  (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
  ```
  
I resolved the issue by using image: dotronglong/faker:2.x
So I would imagine a dockerfile needs tuning up somewhere. 
Apologies if this is not the correct place to put this but hopefully it helps to notify.

Thanks
John

**Comment by dotronglong** [comment]
Hi @John-A-J , sorry for the inconvenience. I believe the issue came from our recent release https://github.com/dotronglong/faker/releases/tag/v3.0.0

I think we forgot to update Docker. Let me check on it. Thank you.

**Comment by dotronglong** [comment]
I believe it should be working now. Please help to verify (ensure to pull new image). Thank you. @John-A-J

**Comment by dotronglong** [comment]
I closed the issue, if you believe it still persists please reopen. Thank you.

**Comment by John-A-J** [comment]
Yes all good, sorry for the terrible delay in reply, thanks
