### ISSUE TITLE
Publish variants of docker images

### ISSUE THREAD

**Issue by snicoll** [dotronglong/faker#56]
When I try to run `faker` `3.0.0` on my Mac M2, I get the following:

```bash
docker run --rm -p 8081:3030 -v ./restmocks:/app/mocks dotronglong/faker:3.0.0
```

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Would it be possible to publish additional images for other cpu architectures?

**Comment by dotronglong** [comment]
Thank you @snicoll . I am checking for it, currently only build for linux. In the meantime, you can build your local image.

`docker build -t dotronglong/faker:3.0.0 .`

(Remember to pull the latest master which introduced some changes in `Dockerfile`)

**Comment by dotronglong** [comment]
Hi @snicoll , I added some versions for linux and macos. Please help to check if it works at your end. Thank you.
